baseURL = "https://thoaitrands.github.io/"
languageCode = "en-us"
title = "Devopsbasic"
theme="archie"
copyright = "© Thor"
disqusShortname = 'tho_i_tr_n'

 # Comment config
[params.page.comment]
enable = true
# Disqus comment config (https://disqus.com/)
[params.page.comment.disqus]
	enable = true
	# Disqus shortname to use Disqus in posts
	shortname = "devopsbasic"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/thoaitrands"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4